name 'formatron_graphite'
version '0.1.1'
description 'Formatron Graphite cookbook'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
source_url 'https://github.com/formatron/graphite-cookbook'
issues_url 'https://github.com/formatron/graphite-cookbook/issues'
supports 'ubuntu'
depends 'build-essential'
depends 'formatron_postgresql'
